
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jul 30 23:23:51 CST 2015
//----------------------------------------------------

package practicacompi1s2;

/** CUP generated class containing symbol constants. */
public class Caracter {
  /* terminals */
  public static final int Tk_Pol = 24;
  public static final int Tk_Rojo = 12;
  public static final int Tk_Cua = 21;
  public static final int Tk_Amarillo = 14;
  public static final int Tk_Coma = 2;
  public static final int Tk_Negro = 18;
  public static final int Tk_Deci = 10;
  public static final int Tk_Naranja = 15;
  public static final int Tk_Graf = 19;
  public static final int Tk_Resta = 4;
  public static final int Tk_Puntos = 9;
  public static final int Tk_Line = 22;
  public static final int Tk_Azul = 11;
  public static final int EOF = 0;
  public static final int Tk_Error = 25;
  public static final int Tk_Cerrar = 8;
  public static final int Tk_Verde = 13;
  public static final int Tk_Cir = 20;
  public static final int error = 1;
  public static final int Tk_Abrir = 7;
  public static final int Tk_Morado = 16;
  public static final int Tk_Diag = 5;
  public static final int Tk_Suma = 3;
  public static final int Tk_Por = 6;
  public static final int Tk_Rec = 23;
  public static final int Tk_Cafe = 17;
}

